import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navigator from './components/navigator'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigator></Navigator>
    <button className='btn btn-primary'>My First Button</button>
    
    </div>
    
  )
}
